const projects = [{
    title: "calANdrier",
    ref:"calandrier",
    fileName: "calandrier.png",
    description: "Development of an online annual calendar app for a client. Pushed the app further, improved it and launched it as a PWA SaAs after that.",
    long_description: "This is my most complete project to date, since it is the development of a <span class='text-success font-bold'>complete SaaS from scratch</span>. This App is an <span class='text-success font-bold'>annual calendar</span> with a different layout to visualize your events in a different way. Multiples challenges had to be addressed, including front-end design, back-end architecture, authentication, APIs connection, and manipulating time objects. To achieve a user-friendly and visually appealing interface, I utilized <span class='text-success font-bold'>SvelteKit, Sass, and Typescript</span> for front-end design. The back-end architecture was built using <span class='text-success font-bold'>Javascript and Supabase</span> to ensure scalability and reliability. Additionally, authentication was implemented using Supabase to ensure secure access to the application. To connect with external services such as <span class='text-success font-bold'>Google Agenda or Trello</span>, I used APIs connection to retrieve events in the app. Time objects manipulation was a crucial aspect of the application and was achieved through careful use of Javascript. Finally, to monetize the application and enable payments, I integrated <span class='text-success font-bold'>Stripe</span>. The result is a complete SaaS that is user-friendly, secure, and fully functional.",
    link: "https://app.calandrier.com",
    langs:["sveltekit", "js", "ts", "sass", "postgresql"],
    apis_used:["google-agenda", "outlook", "jira", "supabase", "stripe", "trello"],
    platforms_used:["supabase", "vercel", "stripe", "googlecloud"],
    show_screenshots:true,
},{
    title: "Planification",
    ref:"planification",
    fileName: "gantt.png",
    description: "Development of a Planification App used to monitor and manage the production of vegetables for a client. In order to to simulate the growth of the vegetables I had to integrate different mathematical models to the simulation algorithms.",
    long_description: "Exciting project, about adapting an <span class='text-success font-bold'>open source gantt library</span> I'm used to work with (svelte-gantt) for a client project. The goal of the app is to <span class='text-success font-bold'>simulate and project the growth of vegetables</span> during different timespans (Quarter/Year). The whole app being built on top of to the same db as the client's ERP to link products sells and products growth. An important part of the mission was about <span class='text-success font-bold'>database architecture (MYSQL)</span> to include the objects manipulated, with a lot of <span class='text-success font-bold'>automated actions</span> to be able to fill the production planning fast but as close to reality as possible. Had to integrate <span class='text-success font-bold'>mathematical models</span> to simulate the growth of those vegetables, this was achieved via complex php algorithm on the backend-side. Front-end was built with <span class='text-success font-bold'>Svelte, CSS and JS</span>. Unfortunately the app is available only for the client, but there is possibility to show some screenshots on demand.",
    link: "empty",
    langs:["php", "svelte", "js", "mysql", "css", "bitbucket"],
    apis_used:[],
    platforms_used:["dolibarr"],
    show_screenshots:false,
},{
    title: "Github Projects",
    ref:"github",
    fileName: "brands/github.svg",
    description: "Main maintainer of the svelte-gantt repo during 1 year (328 ⭐). Created svelte-kanban (31 ⭐), and working on different personal projects (using bitbucket for the professional ones). This current portfolio is available on my github!",
    long_description: "After using a very usefull library (<a class='link text-success' href='https://github.com/ANovokmet/svelte-gantt' target='_blank'>svelte-gantt</a> ) for a professional project, decided to propose my help to the maintainer of the repo. After a few months, I was the <span class='text-success font-bold'>main maintainer</span> of it. I worked on it for a year, and then decided to create my own library, <a class='link text-success' href='https://github.com/V-Py/svelte-kanban' target='_blank'>svelte-kanban</a>. I also created a few personal projects, and I'm currently working on a few more. This current portfolio is available on my github <a class='link text-success' href='https://github.com/V-Py/portfolio' target='_blank'>HERE</a>!",
    link: "https://github.com/V-Py" ,
    langs:["sveltekit", "js", "ts", "css",],
    apis_used:[],
    platforms_used:['github', 'supabase'],
    show_screenshots:true,
},{
    title: "Tasks management",
    ref:"tasks",
    fileName: "tasks.png",
    description: "Development of a Task Management application (interface, db structure, interactions) connected to a Dolibarr ERP.",
    long_description: "My first project working with a <span class='text-success font-bold'>web designer</span>, collaborating with <span class='text-success font-bold'>Figma</span>. Really enjoyed the front-end integrator part, very straight-forward and it allowed me to be focus on the technical/dev side of front-end. The app is designed to be used on <span class='text-success font-bold'>tablet and desktop</span>. For the <span class='text-success font-bold'>back-end part (MYSQL and php)</span>, I was in charge to create/adapt the data structure for the app, which is connected to the Dolibarr ERP of the client. Needed to think about different layers of permissions, and interactions for the different tasks available.",
    link: "empty" ,
    langs:["sveltekit", "js", "php", "mysql", "ts", "css",],
    apis_used:[],
    platforms_used:["figma", "dolibarr", "bitbucket"],
    show_screenshots:false,
},{
    title: "Dolibarr Projects",
    ref:"dolibarr",
    fileName: "brands/dolibarr.svg",
    description: "Dolibarr is an open source ERP. I work with it on a daily basis, for a variety of different customers because it is very adaptable, and it often becomes the heart of any business digital processes.",
    long_description: "As a freelance, a big part of my work is to develop custom experiences and modules for clients using <span class='text-success font-bold'>Dolibarr ERP CRM, an open source software written in PHP</span>. Indeed, the vast majority of my clients are small and medium-sized companies realizing what they need to do/improve in their digital transition in order to stay competitive and efficient in their fields. And often, the entry point is an ERP software, since it is generalist, transverse, and mandatory when we talk about business softwares. Dolibarr is a great open source ERP, and I'm very happy to be able to work with it. My next goal is to be able to <span class='text-success font-bold'>contribute</span> a bit more to this amazing project. I love the community, the <span class='text-success font-bold'>open source spirit</span>, and the fact that it is a very powerful tool that can be adapted to a lot of different needs.",
    link: "empty" ,
    langs:["php", "mysql", "css", "js"],
    apis_used:[],
    platforms_used:["dolibarr", "bitbucket"],
    show_screenshots:true,
},{
    title: "Silex",
    ref:"silex",
    fileName: "silex.png",
    description: "Creating a simple website (Fr) for our enterprise Silex, so people can know what we do and contact us.",
    long_description: "Silex is a <span class='text-success font-bold'>software development enterprise</span> I created with two associates. In order to improve our online presence and reach potential customers, we created a <span class='text-success font-bold'>simple landing page</span> in French that will provide information about our company and the services we offer. The primary objective of the website is to make it easy for people to learn more about our enterprise and to contact us if they are interested in working with us. In terms of content, the website includes a brief introduction to Silex, as well as information about our areas of expertise. We also highlight some of the software development services we offer, such as <span class='text-success font-bold'>standard ERP, custom ERP, and custom software development</span>. To make it easy for people to get in touch with us, the website includes a simple <span class='text-success font-bold'>contact form </span>that visitors can fill out to send us a message.",
    link: "https://silex-lab.fr" ,
    langs:["sveltekit", "js", "ts", "css"],
    apis_used:["mailchimp"],
    platforms_used:["mailchimp", "bitbucket"],
    show_screenshots:true,
},{
    title: "Shopify and DHL",
    ref:"shopify",
    fileName: "brands/shopify.svg",
    description: "Connecting a Dolibarr ERP to a Shopify Store to synchronize orders, and also to the DHL SOAP API to generate labels for products shipments.",
    long_description: "Most of my activity as a freelance developer is centered around <span class='text-success font-bold'>Dolibarr ERP</span> an open source software based on <span class='text-success font-bold'>php</span>. Most business companies need a software to manage their activities, and an ERP such as Dolibarr tackles all the basic needs (sales, distribution, production, CRM, accounting, etc). But companies often (always?) need custom developments to adapt the software to the specificity of their activities. On this project, the first need was to <span class='text-success font-bold'>connect the ERP to a Shopify Store</span> to synchronize orders, customers and products using the <span class='text-success font-bold'>Shopify REST API and different php CRON jobs</span>. The second need was to <span class='text-success font-bold'>generate labels with DHL</span> for products shipments using the <span class='text-success font-bold'>DHL SOAP API via XML requests</span> (with very poor documentation, mainly PDF).",
    link: "empty" ,
    langs:["php", "xml", "css", "mysql", "soap"],
    apis_used:["dhl", "shopify"],
    platforms_used:["dhl", "shopify", "dolibarr", "bitbucket"],
    show_screenshots:true,
},{
    title: "Derniere Renovation",
    ref:"derniererenovation",
    fileName: "dernierenovation.png",
    description: "Helped working on a wordpress website for a French ecologic association. ",
    long_description: "After seeing a post from the <span class='text-success font-bold'>association Derniere Renovation</span> on Twitter asking for help from developers for their website, I decided to help. Not because I needed a project (I was working as a freelance in the meantime), but first because <span class='text-success font-bold'>the cause was very important for me</span>. Indeed, this association fights for the energy renovation of buildings, a major subject for those like me concerned about global warming, energy consumption and the environment. I helped them by <span class='text-success font-bold'>creating components for their Wordpress website</span> using <span class='text-success font-bold'>>HTML, CSS and TailwindCSS</span>, based on their design made on <span class='text-success font-bold'>Zeplin</span>. We worked on it as 3 persons, another developer (lead) and a project manager, using <span class='text-success font-bold'>Discord</span> to communicate, and <span class='text-success font-bold'>GitHub</span> for CI/CD.",
    link: "https://derniererenovation.fr/" ,
    langs:["tailwindcss", "css"],
    apis_used:[],
    platforms_used:["wordpress", "figma", "discord", "github", "zeplin"],
    show_screenshots:true,
}]

export default projects;