const projects = [{
    title: "calANdrier",
    ref:"calandrier",
    fileName: "calandrier.png",
    description: "Development of an online annual calendar app for a client. Pushed the app further, improved it and launched it as a SaAs after that.",
    long_description: "Key words : SaAs, SvelteKit, Supabase, Stripe, multiple apis, time handling, interface creating, design and more.",
    link: "https://app.calandrier.com",
    langs:["sveltekit", "js", "ts", "sass",],
    apis_used:["google-agenda", "outlook", "jira", "supabase", "stripe", "trello"],
    platforms_used:["supabase", "vercel", "stripe", "googlecloud"],
},{
    title: "Planification",
    ref:"planification",
    fileName: "gantt.png",
    description: "Development of a Planification App used to monitor and manage the production of vegetables for a client. Had to integrate mathematical models to simulate the growth of those vegetables.",
    long_description: "Adapt an existing library tool for a precise purpose : Ie follow the grow of vegetables. /Had to integrate mathematical models to simulate the growth of those vegetables.",
    link: "empty",
    langs:["php", "svelte", "js", "css"],
    apis_used:[],
    platforms_used:["dolibarr"],
},{
    title: "Gestion des tâches",
    ref:"tasks",
    fileName: "tasks.png",
    description: "Development of a Task Management application (interface, db structure, interactions) connected to a Dolibarr ERP.",
    long_description: "More of an architecture, integrator project. Learning to integrate the front-end part with Figma, create the structure for the backend, ",
    link: "empty" ,
    langs:["sveltekit", "js", "php", "ts", "css",],
    apis_used:[],
    platforms_used:["figma", "dolibarr"],
},{
    title: "Github Projects",
    ref:"github",
    fileName: "brands/github.svg",
    description: "Main maintainer of the svelte-gantt repo during 1 year (328 ⭐). Created svelte-kanban (31 ⭐), and working on different personal projects (using bitbucket for the professional ones). This current portfolio is available on my github!",
    long_description: "After using a very usefull library on the pro side, decided to propose my help to the maintainer of the repo. After a few months, I was kinda the main maintainer of it. I worked on it for a year, and then decided to create my own library, svelte-kanban. I also created a few personal projects, and I'm currently working on a few more. This current portfolio is available on my github!",
    link: "https://github.com/V-Py" ,
    langs:["sveltekit", "js", "ts", "css",],
    apis_used:[],
    platforms_used:['github', 'supabase'],
},{
    title: "Silex",
    ref:"silex",
    fileName: "silex.png",
    description: "Creating a simple website (Fr) for our enterprise Silex, so people can know what we do and contact us.",
    long_description: "After creating a business, had to have a landing page/simple website to address people and show what we do. I created it using SvelteKit, and deployed it on Vercel. I also created a simple contact form, that sends an email to the company's email address.",
    link: "https://silex-lab.fr" ,
    langs:["sveltekit", "js", "ts", "css",],
    apis_used:["mailchimp"],
    platforms_used:["mailchimp"],
},{
    title: "Shopify and DHL",
    ref:"eyelights",
    fileName: "brands/shopify.svg",
    description: "Connecting a Dolibarr ERP to a Shopify Store to synchronize orders, and also to the DHL SOAP API to generate labels for products shipments.",
    long_description: "My activity has always been mainly centred around Dolibarr ERP an Open Source software. On this project, I had to connect it to a Shopify Store to synchronize orders, and also to the DHL SOAP API to generate labels for products shipments.",
    link: "empty" ,
    langs:["php", "xml", "css", "soap"],
    apis_used:["dhl", "shopify"],
    platforms_used:["dhl", "shopify", "dolibarr"],
},{
    title: "Derniere Renovation",
    ref:"dernierenovation",
    fileName: "dernierenovation.png",
    description: "Helped working on a wordpress website for a french ecologic association. ",
    long_description: "After seeing a post on twitter asking for help from developers, I decided to help. I worked on the website, and also on the discord bot that was used to manage the website.",
    link: "https://derniererenovation.fr/" ,
    langs:["tailwindcss", "css"],
    apis_used:[],
    platforms_used:["wordpress", "figma", "discord"],
}]

export default projects;